# Generated by Django 4.0.3 on 2022-06-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inbound_id', models.IntegerField()),
                ('contracted_at', models.DateTimeField()),
                ('contracted_value', models.IntegerField()),
                ('person', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=30)),
                ('client_type', models.CharField(choices=[('ADV', '광고주'), ('AGN', '대행사'), ('LAB', '랩사')], max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('progress', '진행중'), ('end', '종료')], default='진행중', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('inbound_dept', models.CharField(choices=[('CAM', '캠페인본부'), ('NWB', 'BX사업본부'), ('CNS', '전략컨설팅본부'), ('SLT', '더쏠트'), ('LCO', '로코옵티마이저스')], max_length=10)),
                ('inbound_path', models.CharField(max_length=20)),
                ('inbound_title', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=20)),
                ('budget', models.IntegerField(null=True)),
                ('requested_summary', models.CharField(max_length=50)),
                ('client_manager', models.CharField(max_length=5, null=True)),
                ('client_manager_email', models.EmailField(max_length=30, null=True)),
                ('client_manager_tel', models.CharField(max_length=13, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InboundHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ACT1', '응대회신'), ('ACT2', '담당부서 이관'), ('ACT3', '미팅확정'), ('ACT4', '미팅완료')], max_length=10)),
                ('description', models.TextField()),
                ('person', models.CharField(max_length=5)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbt.inbound')),
            ],
        ),
    ]
