# Generated by Django 4.0.3 on 2022-06-01 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('inbound_title', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=20)),
                ('client_contact_point', models.CharField(max_length=20)),
                ('dept', models.CharField(choices=[('CAM', '캠페인본부'), ('BX', 'BX사업본부'), ('CNS', '전략컨설팅본부'), ('SLT', '더쏠트'), ('LCO', '로코옵티마이저스')], default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('assignee', models.CharField(max_length=10)),
                ('contracted_value', models.IntegerField()),
                ('status', models.CharField(max_length=5)),
                ('memo', models.TextField()),
                ('inbound_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mbt.inbound')),
            ],
        ),
    ]
