# Generated by Django 4.0.3 on 2022-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
