# Generated by Django 4.0.5 on 2022-06-08 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contracted_dept',
            field=models.CharField(choices=[('CAM', '캠페인본부'), ('NWB', 'BX사업본부'), ('CNS', '전략컨설팅본부'), ('SLT', '더쏠트'), ('LCO', '로코옵티마이저스')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
