# Generated by Django 3.1.7 on 2022-06-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='inbound_id',
            new_name='inbound',
        ),
    ]
