# Generated by Django 4.0.3 on 2022-06-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbt', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
