# Generated by Django 4.0.5 on 2022-06-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbt', '0002_contract_contracted_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contracted_title',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
