# Generated by Django 4.0.5 on 2022-06-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbt', '0003_contract_contracted_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client_manager',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_manager_email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_manager_tel',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
