# Generated by Django 4.0.5 on 2022-06-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbt', '0005_alter_contract_inbound_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='inboundhistory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
