# Generated by Django 4.0.5 on 2022-06-10 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mbt', '0007_producthistory_billingrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrevenue',
            name='billing_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
